development:
  adapter: postgresql
  database: biscuit_development
  host: localhost
  username: biscuit
  password: biscuit
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: biscuit_test
  host: localhost
  username: biscuit
  password: biscuit
  pool: 5
  timeout: 5000
